### ISSUE TITLE
IntialNode Count MaxCount MinCount Validation

### ISSUE THREAD

**Issue by chrislovecnm** [GoogleCloudPlatform/gke-terraform-generator#22]
The validation for `        initialNodeCount: 2` working weird.

This works
```yaml
  nodePools:
    - metadata:
        name: my-node-pool
      spec:
        minCount: 2
        maxCount: 2
        initialNodeCount: 2
```

This does not work:

```yaml
  nodePools:
    - metadata:
        name: my-node-pool
      spec:
        minCount: 2
        initialNodeCount: 2
```

This does not work:

```yaml
  nodePools:
    - metadata:
        name: my-node-pool
      spec:
        initialNodeCount: 2
```
