### ISSUE TITLE
Using a private registry in same project is not working

### ISSUE THREAD

**Issue by chrislovecnm** [GoogleCloudPlatform/gke-terraform-generator#23]
I have added the missing oauth scope in https://github.com/GoogleCloudPlatform/gke-terraform-generator/pull/21 and for some reason it is not working :(

I am getting docker login issues on the nodes. Here is my yaml in order to recreate:

```yaml
kind: gke-cluster
metadata:
  name: "test-cluster"
spec:
  region: "us-west2"
  private: "false"
  regional: "false"
  zones: 
    - "us-west2-c"
  addons:
    istio: false
    binaryAuth: false
  network:
    metadata:
      name: my-network
    spec:
      subnetName: my-subnet
      subnetRange: "10.0.0.0/24"
      podSubnetRange: "10.1.0.0/16"
      serviceSubnetRange: "10.2.0.0/20"
      masterIPV4CIDRBlock: "172.16.0.16/28"
  nodePools:
    - metadata:
        name: my-node-pool
      spec:
        minCount: 2
        maxCount: 2
        initialNodeCount: 2
        machineType: n1-standard-2
        preemptible: true
```
